### ISSUE TITLE
先膜拜，顺便请教一下大佬

### ISSUE THREAD

**Issue by ssmnr** [chachae/oes-cloud#2]
大佬的项目完成度是不是比较低？
搭建好环境跑起前后端，发现数据库表只有结构，登录不进去，然后仔细看了下数据库结构，发现需要的数据不少，不知道该怎么构造，是新的前后端没有推上来吗？
大佬能否有空更新更新

**Comment by chachae** [comment]
> 大佬的项目完成度是不是比较低？
> 搭建好环境跑起前后端，发现数据库表只有结构，登录不进去，然后仔细看了下数据库结构，发现需要的数据不少，不知道该怎么构造，是新的前后端没有推上来吗？
> 大佬能否有空更新更新

邮箱留一下，给你发数据库数据

**Comment by chachae** [comment]
> 大佬的项目完成度是不是比较低？
> 搭建好环境跑起前后端，发现数据库表只有结构，登录不进去，然后仔细看了下数据库结构，发现需要的数据不少，不知道该怎么构造，是新的前后端没有推上来吗？
> 大佬能否有空更新更新

1. 后端跑 exam-server-dev 分支，前端 master 是最新的
2. 邮箱留一下，给你发数据库数据
